import os
import io
import pytest
from fastapi.testclient import TestClient
from unittest.mock import MagicMock, patch
import numpy as np
import sys

# Ensure backend path is in sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from main import app, get_drive_service_dep, AIGateway

client = TestClient(app)

# --- Mocks ---

# Mock Drive Service
def mock_get_drive_service(x_token: str = None):
    mock = MagicMock()
    # Mock file list needed for finding 'projects' folder and assets
    # structure: list_files returns a list of dictionaries
    # We need to be careful with the logic in main.py
    
    # We will patch the `list_files_in_folder` function in main.py directly instead of mocking the service object too deeply
    return mock

# We will patch the `drive_service` functions imported in main.py
# from drive_service import get_drive_service, upload_json, create_folder, list_files_in_folder, upload_file_stream, get_file_content

@patch('main.create_folder')
@patch('main.list_files_in_folder')
@patch('main.upload_file_stream')
@patch('main.upload_json')
@patch('core.ai_gateway.AIGateway.embed_content')
@patch('core.ai_gateway.AIGateway.get_fast_model')
def test_full_flow(mock_get_fast, mock_embed, mock_upload_json, mock_upload_stream, mock_list_files, mock_create_folder):
    
    print("\nStarting TestClient E2E Flow...")

    # --- Setup Mocks ---
    
    # Mock Drive interactions
    # 1. list_files_in_folder: First call checks for 'projects' folder, return [] to trigger create
    # 2. create_folder: returns 'mock_projects_id'
    # 3. next create_folder: assets, returns 'mock_assets_id'
    
    mock_list_files.side_effect = [
        [], # Projects folder check -> Not found
        [], # Assets folder check -> Not found
        [], # Autocomplete assets check -> Found but empty? Or we mock 'vectors.json' if we wanted file-based, but we are DB based now!
            # Wait, autocomplete still has logic to look for assets, but we updated it to use DB?
            # Let's check the code: Autocomplete uses DB now for retrieval.
    ]
    
    mock_create_folder.return_value = "mock_folder_id"
    mock_upload_stream.return_value = "mock_file_id"
    
    # Mock Embeddings: Return random 768d vector
    mock_embed.return_value = {'embedding': np.random.rand(768).tolist()}
    
    # Mock GenAI Generation
    mock_model = MagicMock()
    mock_model.generate_content.return_value.text = "This is a comprehensive answer generated by the AI."
    mock_get_fast.return_value = mock_model
    
    # Dependency Override for headers
    app.dependency_overrides[get_drive_service_dep] = lambda: MagicMock()

    headers = {
        "X-Gemini-Key": "mock_key",
        "X-Google-Drive-Token": "mock_token" # Overridden but good to have
    }

    # --- 1. Create Project ---
    print("[1] Creating Project...")
    project_payload = {
        "title": "Neon Test Project",
        "pico": {"p": "test", "i": "test", "c": "test", "o": "test"}
    }
    res = client.post("/api/v1/projects/create", json=project_payload, headers=headers)
    assert res.status_code == 200, f"Create failed: {res.text}"
    project = res.json()
    project_id = project['id']
    print(f"Project Created: {project_id}")
    
    # --- 2. Upload PDF ---
    print("[2] Uploading PDF...")
    # Generate dummy PDF content
    pdf_content = b"%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 612 792] /Contents 5 0 R >>\nendobj\n4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n5 0 obj\n<< /Length 44 >>\nstream\nBT /F1 12 Tf 100 700 Td (Neon DB Vectors Test) Tj ET\nendstream\nendobj\nxref\n0 6\n0000000000 65535 f \n0000000010 00000 n \n0000000060 00000 n \n0000000117 00000 n \n0000000255 00000 n \n0000000343 00000 n \ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n436\n%%EOF"
    
    files = {'file': ('test.pdf', pdf_content, 'application/pdf')}
    res = client.post(f"/api/v1/files/upload_pdf?project_id={project_id}", files=files, headers=headers)
    assert res.status_code == 200, f"Upload failed: {res.text}"
    print(f"Upload Success: {res.json()}")

    # --- 3. Chat RAG ---
    print("[3] Testing Chat...")
    res = client.post("/api/v1/ai/chat_with_docs", json={"query": "Vectors", "project_id": project_id}, headers=headers)
    assert res.status_code == 200, f"Chat failed: {res.text}"
    print(f"Chat Response: {res.json()}")
    assert "comprehensive answer" in res.json()['answer']
    
    # --- 4. Autocomplete ---
    print("[4] Testing Autocomplete...")
    res = client.post("/api/v1/ai/autocomplete", json={"text": "Hello world", "cursor_position": 5, "project_id": project_id}, headers=headers)
    assert res.status_code == 200, f"Autocomplete failed: {res.text}"
    print(f"Autocomplete Response: {res.json()}")

    print("\nSUCCESS: Database Migration Verified via E2E Test.")

if __name__ == "__main__":
    # Manually run the test function
    try:
        # We need to manually set up patches since we aren't using pytest runner
        # This is a bit hacky for a script, but works
        test_full_flow()
            
    except Exception as e:
        print(f"TEST FAILED: {e}")
        import traceback
        traceback.print_exc()
